// Unified API Handler - Consolidates multiple endpoints to stay under Vercel Hobby limit
const news = require('./news.js');














































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































</html></body>  </script>    });      loadOverview();      // Load initial data      });        tab.addEventListener('click', () => switchTab(tab.dataset.tab));      document.querySelectorAll('.tab').forEach(tab => {      // Tab click handlers    document.addEventListener('DOMContentLoaded', () => {    // ═══════════════════════════════════════════════════════════════════════════    //                              INIT    // ═══════════════════════════════════════════════════════════════════════════    }      loadTabData(currentTab);      dataCache = {};    function refreshData() {    }      }          break;          if (!dataCache.trending) loadTrending();        case 'trending':          break;          if (!dataCache.raises) loadRaises();        case 'raises':          break;          if (!dataCache.stablecoins) loadStablecoins();        case 'stablecoins':          break;          if (!dataCache.fees) loadDex();        case 'dex':          break;          if (!dataCache.yields) loadYields();        case 'yields':          break;          if (!dataCache.chains) loadChains();        case 'chains':          break;          if (!dataCache.protocols) loadProtocols();        case 'protocols':          break;          if (!dataCache.overview) loadOverview();        case 'overview':      switch (tabName) {    function loadTabData(tabName) {    }      loadTabData(tabName);      // Load data if needed      currentTab = tabName;      document.getElementById(`tab-${tabName}`).classList.add('active');      document.querySelectorAll('.tab-content').forEach(c => c.classList.remove('active'));      // Update content      document.querySelector(`[data-tab="${tabName}"]`).classList.add('active');      document.querySelectorAll('.tab').forEach(t => t.classList.remove('active'));      // Update tab buttons    function switchTab(tabName) {    // ═══════════════════════════════════════════════════════════════════════════    //                              TAB MANAGEMENT    // ═══════════════════════════════════════════════════════════════════════════    }      document.getElementById('trending-content').style.display = 'block';      document.getElementById('trending-loading').style.display = 'none';      `).join('') || '<p>No trending tokens</p>';        </div>          </div>            <code style="font-size: 0.7rem; color: var(--text-muted); word-break: break-all;">${t.address?.slice(0, 20)}...</code>          <div style="margin-top: 8px;">          </div>            <span class="chain-badge">${t.chain}</span>            </div>              ${t.description || 'Unknown Token'}              ${t.icon ? `<img src="${t.icon}" style="width: 24px; height: 24px; border-radius: 50%;">` : '🔥'}            <div class="card-title" style="display: flex; align-items: center; gap: 8px;">          <div class="card-header">        <div class="info-card">      document.getElementById('trending-cards').innerHTML = data.tokens?.map(t => `      dataCache.trending = data;      if (!data) return;      const data = await fetchAPI('trending');      document.getElementById('trending-content').style.display = 'none';      document.getElementById('trending-loading').style.display = 'flex';    async function loadTrending() {    }      document.getElementById('raises-content').style.display = 'block';      document.getElementById('raises-loading').style.display = 'none';      `).join('') || '<p>No potential airdrops found</p>';        </div>          </div>            <span class="card-tag">${a.category || 'Crypto'}</span>          <div class="card-tags">          </div>            </div>              <span class="card-stat-value" style="font-size: 0.9rem">${a.round || '-'}</span>              <span class="card-stat-label">Round</span>            <div class="card-stat">            </div>              <span class="card-stat-value">${formatNumber(a.raised)}</span>              <span class="card-stat-label">Raised</span>            <div class="card-stat">          <div class="card-stats">          </div>            <span class="card-badge" style="background: rgba(251, 191, 36, 0.15); color: var(--accent-yellow)">🪂 Airdrop</span>            <div class="card-title">${a.name}</div>          <div class="card-header">        <div class="info-card">      document.getElementById('airdrops-cards').innerHTML = data.potentialAirdrops?.map(a => `      // Potential airdrops      `).join('') || '<p>No recent raises</p>';        </div>          </div>            ${r.leadInvestors?.slice(0, 2).map(inv => `<span class="card-tag" style="background: rgba(139, 92, 246, 0.15); color: var(--accent-purple)">${inv}</span>`).join('') || ''}            <span class="card-tag">${r.category || 'Crypto'}</span>          <div class="card-tags">          </div>            </div>              <span class="card-stat-value" style="font-size: 0.9rem">${new Date(r.date).toLocaleDateString()}</span>              <span class="card-stat-label">Date</span>            <div class="card-stat">            </div>              <span class="card-stat-value">${formatNumber(r.amount)}</span>              <span class="card-stat-label">Amount</span>            <div class="card-stat">          <div class="card-stats">          </div>            <span class="card-badge" style="background: rgba(34, 197, 94, 0.15); color: var(--accent-green)">${r.round || 'Raise'}</span>            <div class="card-title">${r.name}</div>          <div class="card-header">        <div class="info-card">      document.getElementById('raises-cards').innerHTML = data.raises?.slice(0, 12).map(r => `      // Recent raises      `;        </div>          <div class="stat-value">${data.potentialAirdrops?.length || 0}</div>          <div class="stat-label">Potential Airdrops</div>        <div class="stat-card">        </div>          <div class="stat-value">${data.raisesCount || 0}</div>          <div class="stat-label">Number of Raises</div>        <div class="stat-card">        </div>          <div class="stat-value">${formatNumber(data.totalRaised)}</div>          <div class="stat-label">Total Raised (30d)</div>        <div class="stat-card">      document.getElementById('raises-stats').innerHTML = `      // Stats      dataCache.raises = data;      if (!data) return;      const data = await fetchAPI('raises?days=30');      document.getElementById('raises-content').style.display = 'none';      document.getElementById('raises-loading').style.display = 'flex';    async function loadRaises() {    }      document.getElementById('stablecoins-content').style.display = 'block';      document.getElementById('stablecoins-loading').style.display = 'none';      `).join('') || '<p>No data</p>';        </div>          </div>            <div class="progress-fill purple" style="width: ${(c.supply / maxSupply) * 100}%"></div>          <div class="progress-bar">          </div>            <span style="font-size: 0.85rem; font-family: var(--font-mono)">${formatNumber(c.supply)}</span>            <span style="font-size: 0.85rem; color: var(--text-primary)">${c.chain}</span>          <div style="display: flex; justify-content: space-between; margin-bottom: 4px;">        <div style="margin-bottom: 12px;">      document.getElementById('stables-by-chain').innerHTML = data.byChain?.map(c => `      const maxSupply = data.byChain?.[0]?.supply || 1;      // By chain      `).join('') || '<tr><td colspan="5">No data</td></tr>';        </tr>          <td class="change-value ${getChangeClass(s.change24h)}">${formatPercent(s.change24h)}</td>          <td>${s.dominance}%</td>          <td class="tvl-value">${formatNumber(s.supply)}</td>          </td>            </div>              <span class="protocol-symbol">${s.symbol}</span>              <span class="protocol-title">${s.name}</span>            <div class="protocol-info">          <td>          <td>${i + 1}</td>        <tr>      tbody.innerHTML = data.stablecoins?.map((s, i) => `      const tbody = document.querySelector('#stablecoins-table tbody');      `;        </div>          <div class="stat-value" style="color: var(--accent-${data.signals?.supplyTrend === 'GROWING' ? 'green' : 'red'})">${data.signals?.supplyTrend || '-'}</div>          <div class="stat-label">Supply Trend</div>        <div class="stat-card">        </div>          <div class="stat-value">${data.signals?.dominant || '-'}</div>          <div class="stat-label">Dominant Stablecoin</div>        <div class="stat-card">        </div>          <div class="stat-value">${formatNumber(data.totalSupply)}</div>          <div class="stat-label">Total Supply</div>        <div class="stat-card">      document.getElementById('stablecoins-stats').innerHTML = `      // Stats      dataCache.stablecoins = data;      if (!data) return;      const data = await fetchAPI('stablecoins');      document.getElementById('stablecoins-content').style.display = 'none';      document.getElementById('stablecoins-loading').style.display = 'flex';    async function loadStablecoins() {    }      document.getElementById('dex-content').style.display = 'block';      document.getElementById('dex-loading').style.display = 'none';      `).join('') || '<tr><td colspan="7">No data</td></tr>';        </tr>          <td class="change-value ${getChangeClass(p.change7d)}">${formatPercent(p.change7d)}</td>          <td>${p.revenueShare}%</td>          <td class="volume-value">${p.revenue24h ? formatNumber(p.revenue24h) : '-'}</td>          <td class="volume-value">${formatNumber(p.fees7d)}</td>          <td class="volume-value">${formatNumber(p.fees24h)}</td>          <td style="font-weight: 600; color: var(--text-primary)">${p.name}</td>          <td>${i + 1}</td>        <tr>      tbody.innerHTML = data.protocols?.map((p, i) => `      const tbody = document.querySelector('#fees-table tbody');      `;        </div>          <div class="stat-value" style="font-size: 1.2rem">${data.topRevenueGenerator || '-'}</div>          <div class="stat-label">Top Revenue Generator</div>        <div class="stat-card">        </div>          <div class="stat-value" style="font-size: 1.2rem">${data.topFeeGenerator || '-'}</div>          <div class="stat-label">Top Fee Generator</div>        <div class="stat-card">        </div>          <div class="stat-value">${formatNumber(data.total7d)}</div>          <div class="stat-label">Total Fees 7d</div>        <div class="stat-card">        </div>          <div class="stat-value">${formatNumber(data.total24h)}</div>          <div class="stat-label">Total Fees 24h</div>        <div class="stat-card">      document.getElementById('dex-stats').innerHTML = `      // Stats      dataCache.fees = data;      if (!data) return;      const data = await fetchAPI('fees');      document.getElementById('dex-content').style.display = 'none';      document.getElementById('dex-loading').style.display = 'flex';    async function loadDex() {    }      document.getElementById('yields-content').style.display = 'block';      document.getElementById('yields-loading').style.display = 'none';      `).join('') || '<tr><td colspan="8">No data</td></tr>';        </tr>          <td>${y.stablecoin ? '<span class="card-tag">Stable</span>' : y.ilRisk ? '<span class="card-tag" style="background: rgba(239, 68, 68, 0.15); color: var(--accent-red)">IL Risk</span>' : '-'}</td>          </td>            </div>              <span style="font-size: 0.8rem">${y.quality}</span>              </div>                <div class="quality-fill ${y.quality > 70 ? 'high' : y.quality > 40 ? 'medium' : 'low'}" style="width: ${y.quality}%"></div>              <div class="quality-bar">            <div class="quality-score">          <td>          <td class="tvl-value">${formatNumber(y.tvl)}</td>          <td style="color: var(--accent-green); font-weight: 600; font-family: var(--font-mono)">${y.apy?.toFixed(2)}%</td>          <td><span class="chain-badge">${y.chain}</span></td>          <td>${y.project}</td>          <td style="font-weight: 600; color: var(--text-primary)">${y.pool}</td>          <td>${i + 1}</td>        <tr>      tbody.innerHTML = data.yields?.map((y, i) => `      const tbody = document.querySelector('#yields-table tbody');      `;        </div>          <div class="stat-value">${data.stats?.sustainableCount || 0} / ${data.filteredCount || 0}</div>          <div class="stat-label">Sustainable Yields</div>        <div class="stat-card">        </div>          <div class="stat-value">${data.stats?.medianApy?.toFixed(2) || '-'}%</div>          <div class="stat-label">Median APY</div>        <div class="stat-card">        </div>          <div class="stat-value" style="color: var(--accent-green)">${data.stats?.avgApy?.toFixed(2) || '-'}%</div>          <div class="stat-label">Avg APY (Top Pools)</div>        <div class="stat-card">        </div>          <div class="stat-value">${data.totalPools?.toLocaleString() || '-'}</div>          <div class="stat-label">Total Pools</div>        <div class="stat-card">      document.getElementById('yields-stats').innerHTML = `      // Stats      dataCache.yields = data;      if (!data) return;      const data = await fetchAPI('yields?limit=50');      document.getElementById('yields-content').style.display = 'none';      document.getElementById('yields-loading').style.display = 'flex';    async function loadYields() {    }      document.getElementById('chains-content').style.display = 'block';      document.getElementById('chains-loading').style.display = 'none';      `).join('') || '<tr><td colspan="6">No data</td></tr>';        </tr>          <td class="volume-value">${c.dexVolume24h ? formatNumber(c.dexVolume24h) : '-'}</td>          <td>${c.protocolCount}</td>          </td>            </div>              <span style="font-size: 0.85rem">${c.dominance}%</span>              </div>                <div class="quality-fill ${parseFloat(c.dominance) > 10 ? 'high' : parseFloat(c.dominance) > 2 ? 'medium' : 'low'}" style="width: ${Math.min(100, c.dominance * 2)}%"></div>              <div class="quality-bar">            <div class="quality-score">          <td>          <td class="tvl-value">${formatNumber(c.tvl)}</td>          <td style="font-weight: 600; color: var(--text-primary)">${c.name}</td>          <td>${i + 1}</td>        <tr>      tbody.innerHTML = data.chains?.slice(0, 30).map((c, i) => `      const tbody = document.querySelector('#chains-table tbody');      dataCache.chains = data;      if (!data) return;      const data = await fetchAPI('chains');      document.getElementById('chains-content').style.display = 'none';      document.getElementById('chains-loading').style.display = 'flex';    async function loadChains() {    }      document.getElementById('protocols-content').style.display = 'block';      document.getElementById('protocols-loading').style.display = 'none';      `).join('') || '<tr><td colspan="9">No data</td></tr>';        </tr>          </td>            </div>              ${p.chains?.length > 3 ? `<span class="chain-badge">+${p.chains.length - 3}</span>` : ''}              ${(p.chains || []).slice(0, 3).map(c => `<span class="chain-badge">${c}</span>`).join('')}            <div class="chain-badges">          <td>          <td><span class="signal-badge ${getSignalClass(p.signal)}">${p.signal === 'BULLISH' ? '🟢' : p.signal === 'BEARISH' ? '🔴' : '🟡'} ${p.signal || 'NEUTRAL'}</span></td>          <td class="volume-value">${p.fees24h ? formatNumber(p.fees24h) : '-'}</td>          <td class="change-value ${getChangeClass(p.change30d)}">${formatPercent(p.change30d)}</td>          <td class="change-value ${getChangeClass(p.change7d)}">${formatPercent(p.change7d)}</td>          <td class="tvl-value">${formatNumber(p.tvl)}</td>          <td><span class="chain-badge">${p.category || 'Other'}</span></td>          </td>            </div>              </div>                <span class="protocol-symbol">${p.symbol || ''}</span>                <span class="protocol-title">${p.name}</span>              <div class="protocol-info">              ${p.logo ? `<img src="${p.logo}" class="protocol-logo" alt="${p.name}">` : '<div class="protocol-logo"></div>'}            <div class="protocol-name">          <td>          <td>${i + 1}</td>        <tr>      tbody.innerHTML = data.protocols?.map((p, i) => `      const tbody = document.querySelector('#protocols-table tbody');      dataCache.protocols = data;      if (!data) return;      const data = await fetchAPI('protocols?limit=50');      document.getElementById('protocols-content').style.display = 'none';      document.getElementById('protocols-loading').style.display = 'flex';    async function loadProtocols() {    }      document.getElementById('overview-content').style.display = 'block';      document.getElementById('overview-loading').style.display = 'none';      `).join('') || '<tr><td colspan="4">No data</td></tr>';        </tr>          <td class="change-value ${getChangeClass(p.change24h)}">${formatPercent(p.change24h)}</td>          <td class="volume-value">${formatNumber(p.volume24h)}</td>          <td style="font-weight: 600; color: var(--text-primary)">${p.name}</td>          <td>${i + 1}</td>        <tr>      perpsBody.innerHTML = data.topPerps?.map((p, i) => `      const perpsBody = document.querySelector('#top-perps-table tbody');      // Top Perps      `).join('') || '<tr><td colspan="4">No data</td></tr>';        </tr>          <td class="change-value ${getChangeClass(d.change24h)}">${formatPercent(d.change24h)}</td>          <td class="volume-value">${formatNumber(d.volume24h)}</td>          <td style="font-weight: 600; color: var(--text-primary)">${d.name}</td>          <td>${i + 1}</td>        <tr>      dexBody.innerHTML = data.topDexes?.map((d, i) => `      const dexBody = document.querySelector('#top-dex-table tbody');      // Top DEXes      `).join('') || '<p>No data</p>';        </div>          </div>            <div class="progress-fill cyan" style="width: ${(c.tvl / maxTvl) * 100}%"></div>          <div class="progress-bar">          </div>            <span style="font-size: 0.85rem; font-family: var(--font-mono)">${formatNumber(c.tvl)}</span>            <span style="font-size: 0.85rem; color: var(--text-primary)">${c.name}</span>          <div style="display: flex; justify-content: space-between; margin-bottom: 4px;">        <div style="margin-bottom: 12px;">      categoryEl.innerHTML = data.categoryBreakdown?.slice(0, 10).map(c => `      const maxTvl = data.categoryBreakdown?.[0]?.tvl || 1;      const categoryEl = document.getElementById('category-breakdown');      // Category breakdown      `).join('') || '<tr><td colspan="6">No data</td></tr>';        </tr>          <td><span class="signal-badge ${getSignalClass(p.change7d > 5 ? 'bullish' : p.change7d < -5 ? 'bearish' : 'neutral')}">${p.change7d > 5 ? '🟢 BULLISH' : p.change7d < -5 ? '🔴 BEARISH' : '🟡 NEUTRAL'}</span></td>          <td class="change-value ${getChangeClass(p.change7d)}">${formatPercent(p.change7d)}</td>          <td class="change-value ${getChangeClass(p.change24h)}">${formatPercent(p.change24h)}</td>          <td class="tvl-value">${formatNumber(p.tvl)}</td>          </td>            </div>              </div>                <span class="protocol-symbol">${p.symbol || ''}</span>                <span class="protocol-title">${p.name}</span>              <div class="protocol-info">              ${p.logo ? `<img src="${p.logo}" class="protocol-logo" alt="${p.name}">` : '<div class="protocol-logo"></div>'}            <div class="protocol-name">          <td>          <td>${i + 1}</td>        <tr>      protocolsBody.innerHTML = data.topProtocols?.slice(0, 10).map((p, i) => `      const protocolsBody = document.querySelector('#top-protocols-table tbody');      // Top protocols table      `;        </div>          <div class="stat-value" style="color: var(--accent-${data.signals?.volumeTrend === 'INCREASING' ? 'green' : 'red'})">${data.signals?.volumeTrend || '-'}</div>          <div class="stat-label">Volume Trend</div>        <div class="stat-card">        </div>          <div class="stat-value" style="color: var(--accent-${data.signals?.tvlTrend === 'BULLISH' ? 'green' : data.signals?.tvlTrend === 'BEARISH' ? 'red' : 'yellow'})">${data.signals?.tvlTrend || '-'}</div>          <div class="stat-label">TVL Trend</div>        <div class="stat-card">        </div>          <div class="stat-value">${formatNumber(data.summary?.derivVolume24h)}</div>          <div class="stat-label">Perps Volume 24h</div>        <div class="stat-card">        </div>          <div class="stat-value">${formatNumber(data.summary?.spotVolume24h)}</div>          <div class="stat-label">Spot DEX Volume 24h</div>        <div class="stat-card">        </div>          <div class="stat-value">${formatNumber(data.summary?.totalStablecoins)}</div>          <div class="stat-label">Stablecoin Supply</div>        <div class="stat-card">        </div>          <div class="stat-value">${formatNumber(data.summary?.totalTvl)}</div>          <div class="stat-label">Total DeFi TVL</div>        <div class="stat-card">      document.getElementById('overview-stats').innerHTML = `      // Stats grid      signalTextEl.textContent = data.signals?.marketSentiment || 'NEUTRAL';      signalEl.className = `market-signal ${getSignalClass(data.signals?.marketSentiment)}`;      const signalTextEl = document.getElementById('marketSignalText');      const signalEl = document.getElementById('marketSignal');      // Update market signal      dataCache.overview = data;      if (!data) return;      const data = await fetchAPI('overview');      document.getElementById('overview-content').style.display = 'none';      document.getElementById('overview-loading').style.display = 'flex';    async function loadOverview() {    // ═══════════════════════════════════════════════════════════════════════════    //                              RENDER FUNCTIONS    // ═══════════════════════════════════════════════════════════════════════════    }      }        return null;        console.error(`API error (${endpoint}):`, err);      } catch (err) {        return await res.json();        if (!res.ok) throw new Error(`HTTP ${res.status}`);        const res = await fetch(`/api/analytics/${endpoint}`);      try {    async function fetchAPI(endpoint) {    // ═══════════════════════════════════════════════════════════════════════════    //                              API CALLS    // ═══════════════════════════════════════════════════════════════════════════    }      return signal.toLowerCase();      if (!signal) return 'neutral';    function getSignalClass(signal) {    }      return '';      if (num < 0) return 'negative';      if (num > 0) return 'positive';    function getChangeClass(num) {    }      return `${sign}${num.toFixed(2)}%`;      const sign = num >= 0 ? '+' : '';      if (num === null || num === undefined) return '-';    function formatPercent(num) {    }      return `$${num.toFixed(decimals)}`;      if (num >= 1e3) return `$${(num / 1e3).toFixed(decimals)}K`;      if (num >= 1e6) return `$${(num / 1e6).toFixed(decimals)}M`;      if (num >= 1e9) return `$${(num / 1e9).toFixed(decimals)}B`;      if (num >= 1e12) return `$${(num / 1e12).toFixed(decimals)}T`;      if (num === null || num === undefined) return '-';    function formatNumber(num, decimals = 2) {    // ═══════════════════════════════════════════════════════════════════════════    //                              UTILITIES    // ═══════════════════════════════════════════════════════════════════════════    let currentTab = 'overview';    let dataCache = {};        // ═══════════════════════════════════════════════════════════════════════════    //                              STATE    // ═══════════════════════════════════════════════════════════════════════════  <script>  </main>    </div>      </div>        </div>          <div class="cards-grid" id="trending-cards"></div>          </div>            <span class="section-subtitle">Boosted/trending tokens across all chains</span>            <h3 class="section-title">🔥 Trending Tokens (DexScreener)</h3>          <div class="section-header">        <div class="section">      <div id="trending-content" style="display: none;">      </div>        <p>Loading trending tokens...</p>        <div class="loading-spinner"></div>      <div class="loading-container" id="trending-loading">    <div class="tab-content" id="tab-trending">    <!-- Trending Tab -->    </div>      </div>        </div>          </div>            <div class="cards-grid" id="airdrops-cards"></div>            </div>              <span class="section-subtitle">Well-funded protocols (>$5M raised)</span>              <h3 class="section-title">🪂 Potential Airdrops</h3>            <div class="section-header">          <div class="section">          </div>            <div class="cards-grid" id="raises-cards"></div>            </div>              <h3 class="section-title">🚀 Recent Raises (30 days)</h3>            <div class="section-header">          <div class="section">        <div class="two-column">        <div class="stats-grid" id="raises-stats"></div>      <div id="raises-content" style="display: none;">      </div>        <p>Loading fundraising data...</p>        <div class="loading-spinner"></div>      <div class="loading-container" id="raises-loading">    <div class="tab-content" id="tab-raises">    <!-- Raises Tab -->    </div>      </div>        </div>          </div>            <div id="stables-by-chain"></div>            </div>              <h3 class="section-title">⛓️ Stablecoins by Chain</h3>            <div class="section-header">          <div class="section">          </div>            </table>              <tbody></tbody>              </thead>                </tr>                  <th>24h Change</th>                  <th>Dominance</th>                  <th>Supply</th>                  <th>Stablecoin</th>                  <th>#</th>                <tr>              <thead>            <table class="data-table" id="stablecoins-table">            </div>              <h3 class="section-title">💵 Top Stablecoins</h3>            <div class="section-header">          <div class="section">        <div class="two-column">        <div class="stats-grid" id="stablecoins-stats"></div>      <div id="stablecoins-content" style="display: none;">      </div>        <p>Loading stablecoin data...</p>        <div class="loading-spinner"></div>      <div class="loading-container" id="stablecoins-loading">    <div class="tab-content" id="tab-stablecoins">    <!-- Stablecoins Tab -->    </div>      </div>        </div>          </div>            </table>              <tbody></tbody>              </thead>                </tr>                  <th>7d Change</th>                  <th>Rev Share</th>                  <th>Revenue 24h</th>                  <th>Fees 7d</th>                  <th>Fees 24h</th>                  <th>Protocol</th>                  <th>#</th>                <tr>              <thead>            <table class="data-table" id="fees-table">          <div style="overflow-x: auto;">          </div>            <h3 class="section-title">💱 Protocol Fees & Revenue</h3>          <div class="section-header">        <div class="section">        <div class="stats-grid" id="dex-stats"></div>      <div id="dex-content" style="display: none;">      </div>        <p>Loading DEX & derivatives data...</p>        <div class="loading-spinner"></div>      <div class="loading-container" id="dex-loading">    <div class="tab-content" id="tab-dex">    <!-- DEX Tab -->    </div>      </div>        </div>          </div>            </table>              <tbody></tbody>              </thead>                </tr>                  <th>Type</th>                  <th>Quality</th>                  <th>TVL</th>                  <th>APY</th>                  <th>Chain</th>                  <th>Project</th>                  <th>Pool</th>                  <th>#</th>                <tr>              <thead>            <table class="data-table" id="yields-table">          <div style="overflow-x: auto;">          </div>            <span class="section-subtitle">Filtered: TVL > $100k, APY < 1000%</span>            <h3 class="section-title">💰 Top Yield Opportunities</h3>          <div class="section-header">        <div class="section">        <div class="stats-grid" id="yields-stats"></div>      <div id="yields-content" style="display: none;">      </div>        <p>Loading yield opportunities...</p>        <div class="loading-spinner"></div>      <div class="loading-container" id="yields-loading">    <div class="tab-content" id="tab-yields">    <!-- Yields Tab -->    </div>      </div>        </div>          </div>            </table>              <tbody></tbody>              </thead>                </tr>                  <th>DEX Volume 24h</th>                  <th>Protocols</th>                  <th>Dominance</th>                  <th>TVL</th>                  <th>Chain</th>                  <th>#</th>                <tr>              <thead>            <table class="data-table" id="chains-table">          <div style="overflow-x: auto;">          </div>            <h3 class="section-title">⛓️ Chain Analytics</h3>          <div class="section-header">        <div class="section">      <div id="chains-content" style="display: none;">      </div>        <p>Loading chains...</p>        <div class="loading-spinner"></div>      <div class="loading-container" id="chains-loading">    <div class="tab-content" id="tab-chains">    <!-- Chains Tab -->    </div>      </div>        </div>          </div>            </table>              <tbody></tbody>              </thead>                </tr>                  <th>Chains</th>                  <th>Signal</th>                  <th>Fees 24h</th>                  <th>30d Change</th>                  <th>7d Change</th>                  <th>TVL</th>                  <th>Category</th>                  <th>Protocol</th>                  <th>#</th>                <tr>              <thead>            <table class="data-table" id="protocols-table">          <div style="overflow-x: auto;">          </div>            <span class="section-subtitle">Bullish/Bearish indicators based on TVL, fees, and momentum</span>            <h3 class="section-title">🏛️ Tradeable Protocols with Signals</h3>          <div class="section-header">        <div class="section">      <div id="protocols-content" style="display: none;">      </div>        <p>Loading protocols...</p>        <div class="loading-spinner"></div>      <div class="loading-container" id="protocols-loading">    <div class="tab-content" id="tab-protocols">    <!-- Protocols Tab -->    </div>      </div>        </div>          </div>            </table>              <tbody></tbody>              </thead>                </tr>                  <th>Change</th>                  <th>Volume 24h</th>                  <th>Protocol</th>                  <th>#</th>                <tr>              <thead>            <table class="data-table" id="top-perps-table">            </div>              <h3 class="section-title">📈 Top Perps by Volume</h3>            <div class="section-header">          <div class="section">          </div>            </table>              <tbody></tbody>              </thead>                </tr>                  <th>Change</th>                  <th>Volume 24h</th>                  <th>DEX</th>                  <th>#</th>                <tr>              <thead>            <table class="data-table" id="top-dex-table">            </div>              <h3 class="section-title">🔄 Top DEXes by Volume</h3>            <div class="section-header">          <div class="section">        <div class="two-column">        <!-- Top DEXes & Perps -->        </div>          </div>            <div id="category-breakdown"></div>            </div>              <h3 class="section-title">📊 Category Breakdown</h3>            <div class="section-header">          <div class="section">          <!-- Category Breakdown -->                    </div>            </div>              </table>                <tbody></tbody>                </thead>                  </tr>                    <th>Signal</th>                    <th>7d</th>                    <th>24h</th>                    <th>TVL</th>                    <th>Protocol</th>                    <th>#</th>                  <tr>                <thead>              <table class="data-table" id="top-protocols-table">            <div style="overflow-x: auto;">            </div>              <h3 class="section-title">🏆 Top Protocols by TVL</h3>            <div class="section-header">          <div class="section">          <!-- Top Protocols -->        <div class="two-column">        <!-- Two Column Layout -->                <div class="stats-grid" id="overview-stats"></div>        <!-- Stats Grid -->      <div id="overview-content" style="display: none;">      </div>        <p>Loading market overview...</p>        <div class="loading-spinner"></div>      <div class="loading-container" id="overview-loading">    <div class="tab-content active" id="tab-overview">    <!-- Overview Tab -->  <main class="main-content">  <!-- Main Content -->  </div>    </div>      <button class="tab" data-tab="trending">🔥 Trending</button>      <button class="tab" data-tab="raises">🚀 Fundraising</button>      <button class="tab" data-tab="stablecoins">💵 Stablecoins</button>      <button class="tab" data-tab="dex">🔄 DEX & Perps</button>      <button class="tab" data-tab="yields">💰 Yields</button>      <button class="tab" data-tab="chains">⛓️ Chains</button>      <button class="tab" data-tab="protocols">🏛️ Protocols</button>      <button class="tab active" data-tab="overview">📈 Overview</button>    <div class="tabs">  <div class="tabs-container">  <!-- Tabs -->  </header>    </div>      </button>        <span>↻</span> Refresh      <button class="refresh-btn" onclick="refreshData()">      </div>        <span id="marketSignalText">Loading...</span>        <span>●</span>      <div class="market-signal neutral" id="marketSignal">    <div class="header-right">    </div>      <h1 class="header-title">📊 Analytics Dashboard</h1>      <a href="/" class="back-link">← Home</a>    <div class="header-left">  <header class="header">  <!-- Header --><body></head>  </style>    }      }        grid-template-columns: repeat(2, 1fr);      .stats-grid {      }        padding: 10px 12px;      .data-table th, .data-table td {      }        font-size: 0.85rem;      .data-table {      }        padding: 12px 16px;      .tabs-container {      }        padding: 16px;      .main-content {      }        gap: 12px;        flex-wrap: wrap;        padding: 12px 16px;      .header {    @media (max-width: 768px) {    /* ═══════════════════════════════════════════════════════════════════════ */    /*                              RESPONSIVE                                 */    /* ═══════════════════════════════════════════════════════════════════════ */    }      background: rgba(255, 255, 255, 0.2);    ::-webkit-scrollbar-thumb:hover {    }      border-radius: 4px;      background: rgba(255, 255, 255, 0.1);    ::-webkit-scrollbar-thumb {    }      background: rgba(255, 255, 255, 0.02);    ::-webkit-scrollbar-track {    }      height: 8px;      width: 8px;    ::-webkit-scrollbar {    /* ═══════════════════════════════════════════════════════════════════════ */    /*                              SCROLLBAR                                  */    /* ═══════════════════════════════════════════════════════════════════════ */    .quality-fill.low { background: var(--accent-red); }    .quality-fill.medium { background: var(--accent-yellow); }    .quality-fill.high { background: var(--accent-green); }    }      transition: width 0.3s ease;      border-radius: 3px;      height: 100%;    .quality-fill {    }      overflow: hidden;      border-radius: 3px;      background: rgba(255, 255, 255, 0.1);      height: 6px;      width: 60px;    .quality-bar {    }      gap: 8px;      align-items: center;      display: flex;    .quality-score {    /* ═══════════════════════════════════════════════════════════════════════ */    /*                              QUALITY SCORE                              */    /* ═══════════════════════════════════════════════════════════════════════ */    }      }        grid-template-columns: 1fr;      .two-column {    @media (max-width: 1200px) {    }      gap: 24px;      grid-template-columns: 1fr 1fr;      display: grid;    .two-column {    /* ═══════════════════════════════════════════════════════════════════════ */    /*                              TWO COLUMN                                 */    /* ═══════════════════════════════════════════════════════════════════════ */    }      to { transform: rotate(360deg); }    @keyframes spin {    }      margin-bottom: 16px;      animation: spin 1s linear infinite;      border-radius: 50%;      border-top-color: var(--accent-cyan);      border: 3px solid var(--border-color);      height: 40px;      width: 40px;    .loading-spinner {    }      color: var(--text-muted);      padding: 80px 20px;      justify-content: center;      align-items: center;      flex-direction: column;      display: flex;    .loading-container {    /* ═══════════════════════════════════════════════════════════════════════ */    /*                              LOADING                                    */    /* ═══════════════════════════════════════════════════════════════════════ */    .progress-fill.green { background: var(--accent-green); }    .progress-fill.purple { background: var(--accent-purple); }    .progress-fill.cyan { background: var(--accent-cyan); }    }      transition: width 0.5s ease;      border-radius: 3px;      height: 100%;    .progress-fill {    }      overflow: hidden;      border-radius: 3px;      background: rgba(255, 255, 255, 0.1);      height: 6px;    .progress-bar {    /* ═══════════════════════════════════════════════════════════════════════ */    /*                              PROGRESS BAR                               */    /* ═══════════════════════════════════════════════════════════════════════ */    }      color: var(--accent-cyan);      background: rgba(14, 165, 233, 0.15);      border-radius: 4px;      padding: 2px 8px;      font-size: 0.7rem;    .card-tag {    }      flex-wrap: wrap;      gap: 6px;      display: flex;    .card-tags {    }      font-family: var(--font-mono);      color: var(--text-primary);      font-weight: 600;      font-size: 1.1rem;    .card-stat-value {    }      text-transform: uppercase;      color: var(--text-muted);      font-size: 0.7rem;    .card-stat-label {    }      flex-direction: column;      display: flex;    .card-stat {    }      margin-bottom: 12px;      gap: 16px;      display: flex;    .card-stats {    }      font-weight: 600;      border-radius: 4px;      padding: 3px 8px;      font-size: 0.7rem;    .card-badge {    }      color: var(--text-primary);      font-weight: 600;      font-size: 1rem;    .card-title {    }      margin-bottom: 12px;      align-items: flex-start;      justify-content: space-between;      display: flex;    .card-header {    }      transform: translateY(-2px);      border-color: var(--border-hover);    .info-card:hover {    }      transition: all 0.2s;      padding: 20px;      border-radius: 12px;      border: 1px solid var(--border-color);      background: var(--bg-card);    .info-card {    }      gap: 16px;      grid-template-columns: repeat(auto-fill, minmax(300px, 1fr));      display: grid;    .cards-grid {    /* ═══════════════════════════════════════════════════════════════════════ */    /*                              CARDS GRID                                 */    /* ═══════════════════════════════════════════════════════════════════════ */    }      font-family: var(--font-mono);      color: var(--text-primary);      font-weight: 600;    .tvl-value, .volume-value {    .change-value.negative { color: var(--accent-red); }    .change-value.positive { color: var(--accent-green); }    }      font-family: var(--font-mono);      font-weight: 500;    .change-value {    .signal-badge.neutral { background: rgba(251, 191, 36, 0.15); color: var(--accent-yellow); }    .signal-badge.bearish { background: rgba(239, 68, 68, 0.15); color: var(--accent-red); }    .signal-badge.bullish { background: rgba(34, 197, 94, 0.15); color: var(--accent-green); }    }      text-transform: uppercase;      font-weight: 600;      border-radius: 6px;      padding: 4px 10px;      font-size: 0.75rem;      gap: 4px;      align-items: center;      display: inline-flex;    .signal-badge {    }      font-weight: 500;      color: var(--accent-purple);      background: rgba(139, 92, 246, 0.15);      border-radius: 4px;      padding: 2px 8px;      font-size: 0.7rem;    .chain-badge {    }      flex-wrap: wrap;      gap: 4px;      display: flex;    .chain-badges {    }      color: var(--text-muted);      font-size: 0.75rem;    .protocol-symbol {    }      color: var(--text-primary);      font-weight: 600;    .protocol-title {    }      flex-direction: column;      display: flex;    .protocol-info {    }      background: var(--bg-secondary);      border-radius: 50%;      height: 28px;      width: 28px;    .protocol-logo {    }      gap: 10px;      align-items: center;      display: flex;    .protocol-name {    }      background: rgba(255, 255, 255, 0.02);    .data-table tr:hover td {    }      border-bottom: none;    .data-table tr:last-child td {    }      vertical-align: middle;      border-bottom: 1px solid var(--border-color);      font-size: 0.9rem;      padding: 14px 16px;    .data-table td {    }      font-weight: 600;      border-bottom: 1px solid var(--border-color);      background: rgba(0, 0, 0, 0.2);      color: var(--text-muted);      letter-spacing: 0.5px;      text-transform: uppercase;      font-size: 0.75rem;      padding: 14px 16px;      text-align: left;    .data-table th {    }      overflow: hidden;      border-radius: 12px;      border: 1px solid var(--border-color);      background: var(--bg-card);      border-collapse: collapse;      width: 100%;    .data-table {    /* ═══════════════════════════════════════════════════════════════════════ */    /*                              TABLE                                      */    /* ═══════════════════════════════════════════════════════════════════════ */    }      color: var(--text-muted);      font-size: 0.8rem;    .section-subtitle {    }      gap: 8px;      align-items: center;      display: flex;      color: var(--text-primary);      font-family: var(--font-heading);      font-weight: 600;      font-size: 1.1rem;    .section-title {    }      margin-bottom: 16px;      align-items: center;      justify-content: space-between;      display: flex;    .section-header {    }      margin-bottom: 32px;    .section {    /* ═══════════════════════════════════════════════════════════════════════ */    /*                              SECTION                                    */    /* ═══════════════════════════════════════════════════════════════════════ */    .stat-change.negative { color: var(--accent-red); }    .stat-change.positive { color: var(--accent-green); }    }      margin-top: 4px;      font-size: 0.8rem;    .stat-change {    }      color: var(--text-primary);      font-family: var(--font-heading);      font-weight: 700;      font-size: 1.75rem;    .stat-value {    }      margin-bottom: 8px;      color: var(--text-muted);      letter-spacing: 0.5px;      text-transform: uppercase;      font-size: 0.75rem;    .stat-label {    }      background: var(--bg-card-hover);      border-color: var(--border-hover);    .stat-card:hover {    }      transition: all 0.2s;      padding: 20px;      border-radius: 12px;      border: 1px solid var(--border-color);      background: var(--bg-card);    .stat-card {    }      margin-bottom: 32px;      gap: 16px;      grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));      display: grid;    .stats-grid {    /* ═══════════════════════════════════════════════════════════════════════ */    /*                              STATS GRID                                 */    /* ═══════════════════════════════════════════════════════════════════════ */    }      display: block;    .tab-content.active {    }      display: none;    .tab-content {    }      margin: 0 auto;      max-width: 1600px;      padding: 24px 32px;    .main-content {    /* ═══════════════════════════════════════════════════════════════════════ */    /*                              MAIN CONTENT                               */    /* ═══════════════════════════════════════════════════════════════════════ */    }      color: var(--text-primary);      border-color: var(--accent-cyan);      background: linear-gradient(135deg, rgba(14, 165, 233, 0.15), rgba(139, 92, 246, 0.15));    .tab.active {    }      border-color: var(--border-color);      background: var(--bg-card);    .tab:hover {    }      white-space: nowrap;      transition: all 0.2s;      cursor: pointer;      font-weight: 500;      font-size: 0.9rem;      color: var(--text-secondary);      border: 1px solid transparent;      background: transparent;      border-radius: 8px;      padding: 10px 20px;    .tab {    }      overflow-x: auto;      gap: 8px;      display: flex;    .tabs {    }      background: rgba(0, 0, 0, 0.2);      border-bottom: 1px solid var(--border-color);      padding: 16px 32px;    .tabs-container {    /* ═══════════════════════════════════════════════════════════════════════ */    /*                              TABS                                       */    /* ═══════════════════════════════════════════════════════════════════════ */    .refresh-btn.loading { opacity: 0.6; pointer-events: none; }    .refresh-btn:hover { background: var(--bg-card-hover); border-color: var(--border-hover); }    }      transition: all 0.2s;      gap: 6px;      align-items: center;      display: flex;      font-size: 0.85rem;      cursor: pointer;      border-radius: 8px;      padding: 8px 16px;      color: var(--text-secondary);      border: 1px solid var(--border-color);      background: var(--bg-card);    .refresh-btn {    .market-signal.neutral { background: rgba(251, 191, 36, 0.15); color: var(--accent-yellow); border: 1px solid rgba(251, 191, 36, 0.3); }    .market-signal.bearish { background: rgba(239, 68, 68, 0.15); color: var(--accent-red); border: 1px solid rgba(239, 68, 68, 0.3); }    .market-signal.bullish { background: rgba(34, 197, 94, 0.15); color: var(--accent-green); border: 1px solid rgba(34, 197, 94, 0.3); }    }      letter-spacing: 0.5px;      text-transform: uppercase;      font-weight: 600;      font-size: 0.8rem;      border-radius: 20px;      padding: 8px 16px;      gap: 8px;      align-items: center;      display: flex;    .market-signal {    }      gap: 16px;      align-items: center;      display: flex;    .header-right {    }      background-clip: text;      -webkit-text-fill-color: transparent;      -webkit-background-clip: text;      background: linear-gradient(135deg, var(--accent-cyan), var(--accent-purple));      font-family: var(--font-heading);      font-weight: 700;      font-size: 1.5rem;    .header-title {    .back-link:hover { opacity: 0.8; }    }      transition: opacity 0.2s;      gap: 6px;      align-items: center;      display: flex;      font-size: 0.85rem;      text-decoration: none;      color: var(--accent-cyan);    .back-link {    }      gap: 24px;      align-items: center;      display: flex;    .header-left {    }      z-index: 100;      top: 0;      position: sticky;      backdrop-filter: blur(20px);      background: rgba(0, 0, 0, 0.4);      border-bottom: 1px solid var(--border-color);      padding: 16px 32px;      align-items: center;      justify-content: space-between;      display: flex;    .header {    /* ═══════════════════════════════════════════════════════════════════════ */    /*                              HEADER                                     */    /* ═══════════════════════════════════════════════════════════════════════ */    }      min-height: 100vh;      color: var(--text-secondary);      background: linear-gradient(180deg, var(--bg-primary) 0%, var(--bg-secondary) 100%);      font-family: var(--font-body);    body {        * { margin: 0; padding: 0; box-sizing: border-box; }        }      --border-hover: rgba(255, 255, 255, 0.15);      --border-color: rgba(255, 255, 255, 0.08);      --text-muted: #64748b;      --text-secondary: #94a3b8;      --text-primary: #F8FAFC;      --accent-pink: #ec4899;      --accent-orange: #f97316;      --accent-yellow: #fbbf24;      --accent-red: #ef4444;      --accent-green: #22c55e;      --accent-purple: #8B5CF6;      --accent-cyan: #0EA5E9;      --bg-card-hover: rgba(255, 255, 255, 0.05);      --bg-card: rgba(255, 255, 255, 0.025);      --bg-secondary: #0F1629;      --bg-primary: #0A0E17;      --font-mono: 'JetBrains Mono', monospace;      --font-body: 'Inter', sans-serif;      --font-heading: 'Space Grotesk', sans-serif;    :root {  <style>    <link href="https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@400;500;600;700&family=Inter:wght@300;400;500;600;700&family=JetBrains+Mono:wght@400;500;600;700&display=swap" rel="stylesheet">  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>  <link rel="preconnect" href="https://fonts.googleapis.com">    <meta name="description" content="Multi-source DeFi analytics: TVL, yields, protocols, chains, and market signals">  <title>Analytics Dashboard | nexxore</title>  <meta name="viewport" content="width=device-width, initial-scale=1.0">  <meta charset="UTF-8"><head>const trending = require('./trending.js');
const chat = require('./chat.js');
const health = require('./health.js');
const signals = require('./signals.js');
const alphaScanner = require('./alpha-scanner.js');
const alphaScannerV2 = require('./alpha-scanner-v2.js');
const researchRefined = require('./research-refined.js');
const analyst = require('./analyst.js');
const analytics = require('./analytics.js');

module.exports = async (req, res) => {
  const { pathname } = new URL(req.url, `http://${req.headers.host}`);
  
  // Route to appropriate handler
  if (pathname === '/api/news') {
    return news(req, res);
  } else if (pathname === '/api/trending') {
    return trending(req, res);
  } else if (pathname === '/api/chat') {
    return chat(req, res);
  } else if (pathname === '/api/health') {
    return health(req, res);
  } else if (pathname === '/api/signals') {
    return signals(req, res);
  } else if (pathname === '/api/alpha-scanner') {
    return alphaScanner(req, res);
  } else if (pathname === '/api/alpha-scanner-v2') {
    return alphaScannerV2(req, res);
  // Analytics Platform endpoints
  } else if (pathname === '/api/analytics/overview') {
    return analytics.getOverview(req, res);
  } else if (pathname === '/api/analytics/yields') {
    return analytics.getYields(req, res);
  } else if (pathname === '/api/analytics/protocols') {
    return analytics.getProtocols(req, res);
  } else if (pathname === '/api/analytics/chains') {
    return analytics.getChains(req, res);
  } else if (pathname === '/api/analytics/stablecoins') {
    return analytics.getStablecoins(req, res);
  } else if (pathname === '/api/analytics/trending') {
    return analytics.getTrending(req, res);
  } else if (pathname === '/api/analytics/raises') {
    return analytics.getRaises(req, res);
  } else if (pathname === '/api/analytics/fees') {
    return analytics.getFees(req, res);
  } else if (pathname === '/api/analytics/search') {
    return analytics.searchTokens(req, res);
  // Refined Research Agent endpoints
  } else if (pathname === '/api/research/signals') {
    return researchRefined.getSignals(req, res);
  } else if (pathname === '/api/research/scan') {
    return researchRefined.scanMarkets(req, res);
  } else if (pathname.startsWith('/api/research/signal/')) {
    req.params = { protocol: pathname.split('/').pop() };
    return researchRefined.getProtocolSignal(req, res);
  } else if (pathname === '/api/research/regime') {
    return researchRefined.getMarketRegime(req, res);
  } else if (pathname === '/api/research/history') {
    return researchRefined.getAnalysisHistory(req, res);
  // On-Chain Analyst endpoints
  } else if (pathname === '/api/analyst/ecosystem') {
    return analyst.getEcosystemOverview(req, res);
  } else if (pathname === '/api/analyst/narratives') {
    return analyst.getNarratives(req, res);
  } else if (pathname.startsWith('/api/analyst/narrative/')) {
    req.params = { key: pathname.split('/').pop() };
    return analyst.getNarrativeDetail(req, res);
  } else if (pathname === '/api/analyst/airdrops') {
    return analyst.getAirdrops(req, res);
  } else if (pathname === '/api/analyst/airdrops/farming') {
    return analyst.getFarmingOpportunities(req, res);
  } else if (pathname === '/api/analyst/macro') {
    return analyst.getMacroOverview(req, res);
  } else if (pathname === '/api/analyst/sentiment') {
    return analyst.getSentiment(req, res);
  } else if (pathname === '/api/analyst/full') {
    return analyst.getFullAnalysis(req, res);
  } else {
    res.status(404).json({ error: 'Not Found' });
  }
};
